CREATE TABLE [dbo].[T_USER]
(
	[USER_ID] INT NOT NULL PRIMARY KEY, 
    [USERNAME] NVARCHAR(50) NOT NULL, 
    [PASSWORD_HASH] NVARCHAR(MAX) NOT NULL, 
	[EMAIL] NVARCHAR(MAX) NOT NULL,
    [NAME] NCHAR(20) NOT NULL 
)
