CREATE TABLE [dbo].[TM_GAME_MODE_CARD]
(
	[CARD_ID] INT NOT NULL, 
    [GAME_MODE_ID] INT NOT NULL,
	CONSTRAINT [PK_TM_GAME_MODE_CARD] PRIMARY KEY CLUSTERED ([CARD_ID] ASC, [GAME_MODE_ID] ASC),
	CONSTRAINT [FK_TM_GAME_MODE_CARD_TD_GAME_MODE_GAME_MODE_ID] FOREIGN KEY ([GAME_MODE_ID]) REFERENCES [dbo].[TD_GAME_MODE] ([GAME_MODE_ID]),
    CONSTRAINT [FK_TM_GAME_MODE_CARD_TD_CARD_CARD_ID] FOREIGN KEY ([CARD_ID]) REFERENCES [dbo].[TD_CARD] ([CARD_ID])
)
