CREATE TABLE [dbo].[TM_USER_CARD]
(
	[USER_ID] INT NOT NULL, 
    [CARD_ID] INT NOT NULL,
	CONSTRAINT [PK_TM_USER_CARD] PRIMARY KEY CLUSTERED ([USER_ID] ASC, [CARD_ID] ASC),
	CONSTRAINT [FK_TM_USER_CARD_T_CARD_CARD_ID] FOREIGN KEY ([CARD_ID]) REFERENCES [dbo].[TD_CARD] ([CARD_ID]),
    CONSTRAINT [FK_TM_USER_CARD_T_USER_USER_ID] FOREIGN KEY ([USER_ID]) REFERENCES [dbo].[T_USER] ([USER_ID])
)
